create table t_layer_base(id varchar(32) primary key,name varchar(200) not null,description varchar(2000),longitude decimal(8, 4),latitude decimal(8, 4),address varchar(300),mainperson varchar(50),telephone varchar(30),workshop varchar(200),workarea varchar(200),createtime varchar(19) default convert(varchar, getdate(), 120),edittime varchar(19) default convert(varchar,getdate(),120),state int default 1)
exec sp_addextendedproperty N'MS_Description',N'主键',N'user',N'dbo',N'table',N't_layer_base',N'column',N'id'
exec sp_addextendedproperty N'MS_Description',N'名称',N'user',N'dbo',N'table',N't_layer_base',N'column',N'name'
exec sp_addextendedproperty N'MS_Description',N'描述信息',N'user',N'dbo',N'table',N't_layer_base',N'column',N'description'
exec sp_addextendedproperty N'MS_Description',N'经度',N'user',N'dbo',N'table',N't_layer_base',N'column',N'longitude'
exec sp_addextendedproperty N'MS_Description',N'纬度',N'user',N'dbo',N'table',N't_layer_base',N'column',N'latitude'
exec sp_addextendedproperty N'MS_Description',N'地理位置',N'user',N'dbo',N'table',N't_layer_base',N'column',N'address'
exec sp_addextendedproperty N'MS_Description',N'主要负责人',N'user',N'dbo',N'table',N't_layer_base',N'column',N'mainperson'
exec sp_addextendedproperty N'MS_Description',N'联系电话',N'user',N'dbo',N'table',N't_layer_base',N'column',N'telephone'
exec sp_addextendedproperty N'MS_Description',N'所属车间',N'user',N'dbo',N'table',N't_layer_base',N'column',N'workshop'
exec sp_addextendedproperty N'MS_Description',N'所属工区',N'user',N'dbo',N'table',N't_layer_base',N'column',N'workarea'
exec sp_addextendedproperty N'MS_Description',N'创建时间',N'user',N'dbo',N'table',N't_layer_base',N'column',N'createtime'
exec sp_addextendedproperty N'MS_Description',N'修改时间',N'user',N'dbo',N'table',N't_layer_base',N'column',N'edittime'
exec sp_addextendedproperty N'MS_Description',N'状态(0-已删除|1-正常)',N'user',N'dbo',N'table',N't_layer_base',N'column',N'state'